volumes:
  postgres_data:

services:
  postgres:
    image: postgres:18.1
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build: backend
    env_file: .env
    ports:
      - "1111:80"
    depends_on:
      - postgres